### ISSUE TITLE
Minimal SDK version

### ISSUE THREAD

**Issue by lucas34** [VictorAlbertos/RxGcm#5]
Hi,

As seen on the gradle file, the minimal version for the lib is 16. I think the library works with at least 14. Is there a special reason why you require 16 instead?

Also, side question, the minimal SDK version as defined on the android manifest is 9. 

Cheers

**Comment by VictorAlbertos** [comment]
Hi @lucas34

If you check the rates of [adoption platforms versions](http://developer.android.com/intl/es/about/dashboards/index.html) you will see that it is not worth supporting versions prior api 16. We are talking about only 5% of the market, plus this devices will be -probably- much more flaky due to its old hardware/software.

Also, I think when you create an android project on Android Studio the default min version is 16.   

About the difference between build.grade  and manifest file, [Gradle overrides the manifest values](), so I prefer to update build.gradle file rather than manifest. Or for that matters, I don’t care too much about the manifest file ;)

**Comment by carmas123** [comment]
Can you decrease at least 15?

**Comment by carmas123** [comment]
@lucas34 you can use the manifest overriding:

```
<uses-sdk android:targetSdkVersion="14" android:minSdkVersion="14"
    tools:overrideLibrary="victoralbertos.io.rx_gcm"/>
```
