### ISSUE TITLE
Null Pointer Exception at onNotificationReceived

### ISSUE THREAD

**Issue by eymar** [VictorAlbertos/RxGcm#6]
Hi! I'm trying to receive the notification while application is closed (even not in backgroung) and I got NPE:

FATAL EXCEPTION: AsyncTask #1
03-24 10:48:30.279 29868-29889/com.churchblaze.androidapp E/AndroidRuntime: java.lang.NullPointerException
03-24 10:48:30.279 29868-29889/com.churchblaze.androidapp E/AndroidRuntime:     at rx_gcm.internal.RxGcm.onNotificationReceived(RxGcm.java:192)

This line: Application application = this.activitiesLifecycle.getApplication();

Can I use RxGcm to receive notifications when the application is closed?
Thanks!

**Comment by eymar** [comment]
Seems, I found the solution. I call  RxGcm.Notifications.onBackgroundNotification(BackgroundMessageReceiver.class); in onCompleted of register callback and now it works.

**Comment by VictorAlbertos** [comment]
Hi @eymar 

This is really weird. The workaround you have proposed does not make sense to me because that line of code just registers a class in order to be used later as a listener for RxGcm. 

Anyway, I've released a new version which tries to init the class dependencies of RxGcm in case the onCreate method from Android Application class would have some sort of latency. 

``` gradle
dependencies {
    compile 'com.github.VictorAlbertos:RxGcm:0.1.2' 
}
```

But the [docs says](http://developer.android.com/intl/es/reference/android/app/Application.html#onCreate%28%29) this method will be called before any Service initialization. That's why I can't understand how you got the NPE.  

Could you please try this new version (removing the line of code you wrote as a workaround) and let me know if you are getting the NPE again?

Thanks for the feedback!

**Comment by VictorAlbertos** [comment]
I'm closing this issue because lake of feedback. But @eymar feel free to reopened it.
